### PR TITLE
fix: Bug fix uploading and deleting and naming upload files

### LINKED ISSUE #18: [BUG]: files not being uploaded to /uploads
### Describe the bug

the files are not being uploaded to /uploads

### Steps To Reproduce

try to upload any file in materials or labmaterials section.
the file doesn't upload in the uploads directory.

### Expected Behavior

the file should get uploaded in the uploads directory.

### Screenshots/Videos

https://github.com/user-attachments/assets/7de53650-a691-4b1d-9310-c2a921b1f0d2

### What device are you using?

Desktop

### Operating System

MacOS

### What browsers are you seeing the problem on?

Other

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ansh0506**
## Overview

1. This PR fixes or fixes part of #18 .
2. This PR does the following: It fixes the issue that the when uploading a file it does not go in uploads folder and also deleting doesn't work so I fixed this issue and now If pressed upload an delete button it works an intended .
3. This PR also make sure that when you upload a file It saves it by the name as given in title by the user.

## Essential Checklist

- [x] The PR title starts with "Fix #18 ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #18 : ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

https://github.com/user-attachments/assets/963532d3-fe5e-457d-a444-c123942dfd9c

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

File: backend/src/controllers/labController.js [hunk 1]
```diff
@@ -30,11 +32,30 @@ const uploadLabMaterial = asyncHandler(async (req, res, next) => {
   res.json(new ApiResponse(201, labMaterials, "lab material uploaded successfully"));
 });
 
-const deleteLabMaterial = asyncHandler(async (req, res, next) => {
-    const labMaterialToDelete = await prisma.labMaterial.delete({
-      where: { id: +req.params.id }
+const deleteLabMaterial = async (req, res , next) => {
+  try {
```
Comment (ritankarsaha) [inline backend/src/controllers/labController.js:36]: Good work putting the await async block in a try catch !! @Ansh0506

File: backend/src/controllers/uploadController.js [hunk 2]
```diff
@@ -31,11 +33,30 @@ const uploadMaterial = asyncHandler(async (req, res, next) => {
...
+      where: {id: +req.params.id } 
+    });
+
+    if (!deletedMaterial) {
+      return next(new ApiError(404, "Lab material not found"));
+    }
+
+    const filePath = path.join(__dirname,'..','..','uploads',path.basename(deletedMaterial.url));
+
+    try {
```
Comment (ritankarsaha) [inline backend/src/controllers/uploadController.js:48]: Good works on the try catch @Ansh0506 . thought of opening an issue for it. Lol u did here only. Nice work

File: backend/src/middleware/uploadMiddleware.js [hunk 3]
```diff
@@ -1,21 +1,18 @@
...
-
-const uploadDir = path.join(__dirname, '..', 'uploads');
-if (!fs.existsSync(uploadDir)) {
-  fs.mkdirSync(uploadDir);
-}
 
 const storage = multer.diskStorage({
   destination: (req, file, cb) => {
-    cb(null, uploadDir);
+    cb(null, 'uploads/');
```
Comment (ritankarsaha) [inline backend/src/middleware/uploadMiddleware.js:6]: @Ansh0506 , just for a heads up this was the only fix for thr bug ig. Rest are try catch modifications 🙂

File: backend/src/middleware/uploadMiddleware.js [hunk 4]
```diff
@@ -1,21 +1,18 @@
...
-  }
+    const title = req.body.title;
+    const extension = path.extname(file.originalname);
+    const finalName = `${title}${extension}`;
+    cb(null, finalName);
+  },
 });
 
 const upload = multer({ storage });
-module.exports = upload;
```
Comment (ritankarsaha) [inline backend/src/middleware/uploadMiddleware.js:21]: Future heads up - While pushing take note that there are no un-necessary space additions or un-necessary modifcations. For eg this, if u look closely both are same. prolly u added a space by mistake.

File: backend/src/controllers/uploadController.js [hunk 5]
```diff
@@ -31,11 +33,30 @@ const uploadMaterial = asyncHandler(async (req, res, next) => {
...
 });
 
-const deleteUpload = asyncHandler(async (req, res, next) => {
-  const deleted = await prisma.upload.delete({
-    where: { id: +req.params.id }
-  });
-  res.status(200).json(new ApiResponse(200, deleted, "upload deleted successfully"));
-});
+const deleteUpload = async (req, res , next) => {
+  try {
```
Comment (ritankarsaha) [inline backend/src/controllers/uploadController.js:37]: Agree u did nice work on the try catch @Ansh0506 , but no extra points for that sorry 🙂

**Review by ritankarsaha — APPROVED** [review]
